# Generated by Django 2.1.3 on 2019-05-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_predictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictions',
            name='y',
            field=models.CharField(blank=True, choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=100),
        ),
    ]
